baseURL = "https://z1nz0l1n.com/"
defaultContentLanguage = "en"
title = "Z1NZ0L1N"
enableEmoji = true
enableInlineShortcodes = true
disableKinds = ["taxonomy", "section"]
summaryLength = 40
timeZone = "Europe/Paris"

[permalinks]
  dispatches = "/:slug/"

[taxonomies]
  location = "from"

[params]
  description = "Reading, writing, walking. Not (always) at the same time."
  subtitle = "by Anthony Nelzin-Santos"
  est = "est. 2025"
  author = "Anthony Nelzin-Santos"
  authorShort = "Anthony"
  email = "anthony@nelzin.fr"
  baseHue = 298
  dynamicColour = true
  hueAmplitude = 40
  huePeakDay = 172

[[menu.main]]
  name = "Colophon"
  url = "/colophon/"
  weight = 1
[[menu.main]]
  name = "Blogroll"
  url = "/blogroll/"
  weight = 2
[[menu.main]]
  name = "Contact"
  url = "mailto:anthony@nelzin.fr?subject=Contact%20from%20Z1NZ0L1N"
  weight = 3
[[menu.main]]
  name = "Legal"
  url = "/legal/"
  weight = 4
[[menu.main]]
  name = "Styleguide"
  url = "/styleguide/"
  weight = 5

[imaging]
  quality = 82
  resampleFilter = "Lanczos"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser]
  wrapStandAloneImageWithinParagraph = false

[outputs]
  home = ["HTML", "RSS"]

[services.rss]
  limit = 10