name: publish

on:
  push:
    branches: main
  schedule:
    - cron:  '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache resources
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.HUGO_CACHEDIR }}
            resources/_gen
          key: ${{ runner.os }}-hugo-${{ hashFiles('assets/**', 'content/**/*.jpg', 'hugo.toml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-
          
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true
          
      - name: Build site
        run: hugo --minify
        
      - name: Deploy site
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          protocol: ftps
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          local-dir: ./public/
